spring.application.name=Caching_Proxy

server.port=8082
proxy.origin=https://dummyjson.com
# Suppression de proxy.origin pour utiliser --origin directement
# Utilisation d'un cache en mémoire par défaut
spring.cache.cache-names=proxyResponses
spring.cache.caffeine.spec=maximumSize=1_000,expireAfterWrite=10m
logging.level.root=INFO
spring.main.banner-mode=console
